### ISSUE TITLE
media3-decode-ffmpeg-1.3.1.aar does not work?

### ISSUE THREAD

**Issue by JaroslavHerber** [ag2s20150909/media3libs#5]
Hi,

thank you for the hard work. Just noticed, that the FFMPEG aar file doesn't work anymore in media3/exoplayer (also 1.3.1)

This file:
https://github.com/ag2s20150909/media3libs/blob/1.3.1/repo/androidx/media3/media3-decode-ffmpeg/1.3.1/media3-decode-ffmpeg-1.3.1.aar

It works, if the app is installed through android studio, but not if I generate a signed apk and install it from file.

This error happens:

```
FATAL EXCEPTION: ExoPlayer:Playback
Process: de.my_player.example, PID: 29781
java.lang.NoSuchMethodError: No static method create(I)I in class Landroidx/media3/exoplayer/RendererCapabilities; or its super classes (declaration of 'androidx.media3.exoplayer.RendererCapabilities' appears in base.apk)
	at androidx.media3.decoder.ffmpeg.ExperimentalFfmpegVideoRenderer.supportsFormat(ExperimentalFfmpegVideoRenderer.java:78)
	at androidx.media3.exoplayer.trackselection.MappingTrackSelector.findRenderer(MappingTrackSelector.java:513)
	at androidx.media3.exoplayer.trackselection.MappingTrackSelector.selectTracks(MappingTrackSelector.java:380)
	at androidx.media3.exoplayer.MediaPeriodHolder.selectTracks(MediaPeriodHolder.java:256)
	at androidx.media3.exoplayer.MediaPeriodHolder.handlePrepared(MediaPeriodHolder.java:194)
	at androidx.media3.exoplayer.ExoPlayerImplInternal.handlePeriodPrepared(ExoPlayerImplInternal.java:2453)
	at androidx.media3.exoplayer.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:563)
	at android.os.Handler.dispatchMessage(Handler.java:103)
	at android.os.Looper.loop(Looper.java:359)
	at android.os.HandlerThread.run(HandlerThread.java:67)
channel 'ef2c9cd de.my_player.example/de.my_player.example.MainActivity (server)' ~ Channel is unrecoverably broken and will be disposed!
```

**Comment by JaroslavHerber** [comment]
Also media3-decode-ffmpeg-1.3.0.aar has the problem.
Switching back to version 1.2.0 solved the problem - even with androidx/media version 1.3.1.

**Comment by JaroslavHerber** [comment]
I found out, that this issue only happens when minifyEnabled = false
```
buildTypes {
        release {
            minifyEnabled false
        }
}
```
Must be ProGuard related
